name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Deploy to Server
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SERVER_USER: ${{ secrets.SERVER_USER }}
#          SERVER_IP: ${{ secrets.SERVER_IP }}
#        run: |
#          echo "$SSH_PRIVATE_KEY" > private_key
#          chmod 600 private_key
#          scp -i private_key -r * $SERVER_USER@$SERVER_IP:/path/to/your/service
#          ssh -i private_key $SERVER_USER@$SERVER_IP 'sudo systemctl restart your-service'
